site_name: Compiladores | Grupo 1

repo_name: "compiladores-equipe-1"
repo_url: https://github.com/brunna-martins/compiladores-equipe-1

nav:
  - Início: index.md
  - Acompanhamento Semanal:
    - Semana 1: acompanhamento/semana-01.md
    - Semana 2: acompanhamento/semana-02.md
  - Reuniões: 
    - Sprint 2:
      - Ata: reunioes/sprint2/ata.md
      - Pautas: reunioes/sprint2/pautas.md
    - Sprint 3:
      - Ata: reunioes/sprint3/ata.md
      - Pautas: reunioes/sprint3/pautas.md 
  - Entrega 1:
    - Definição do Projeto: entrega1/definicao.md
    - Linguagem Escolhida: entrega1/linguagem.md
    - Cronograma de Sprints: entrega1/cronograma.md 
    - Analisador Léxico:
      - Identifidores e Palavras-chave: entrega1/analisador-lexico/identificadores-palavras-chave.md
      - Literais e Comentários: entrega1/analisador-lexico/literais-comentarios.md
      - Operadores, Delimitadores e erros: entrega1/analisador-lexico/operadores-delimitadores-erros.md
  - Entrega 2:
    - Árvore Sintática: entrega2/arvore-sintatica.md
    - Tabela de Símbolos: entrega2/tabela-simbolos.md    
theme:
  name: material
  language: pt-BR
  highlightjs: true

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

  palette:
    - scheme: default
      primary: ''
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        
    - scheme: slate
      primary: ''
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  

markdown_extensions:
  - tables
  - fenced_code
  - codehilite
  - attr_list
  - pymdownx.tasklist
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences